//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhanMem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuXuatKho
    {
        public Nullable<int> SoLuongXuat { get; set; }
        public string MaXuatKho { get; set; }
        public string MaSanPham { get; set; }
    
        public virtual SanPham SanPham { get; set; }
        public virtual PhieuXuatKho PhieuXuatKho { get; set; }
    }
}
