//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhanMem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kho
    {
        public string MaNhapKho { get; set; }
        public int TongGiaNhap { get; set; }
        public string MaLoai { get; set; }
        public string MaSanPham { get; set; }
    
        public virtual Loai Loai { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
