//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhanMem
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuXuatKho
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuXuatKho()
        {
            this.ChiTietPhieuXuatKhoes = new HashSet<ChiTietPhieuXuatKho>();
        }
    
        public string MaXuatKho { get; set; }
        public Nullable<System.DateTime> NgayXuatKho { get; set; }
        public Nullable<int> TongGiaXuat { get; set; }
        public string MaNhanVien { get; set; }
        public string MaNhapKho { get; set; }
        public string MaKhachHang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieuXuatKho> ChiTietPhieuXuatKhoes { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual Kho Kho { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
